### Implementation of simple neural network for a classification task. 

In [1]:
#Import required libraries 
import keras #library for neural network
import pandas as pd 
import numpy as np 
import pandas as pd 
from sklearn.preprocessing import normalize #machine learning algorithm library

Using TensorFlow backend.


In [9]:
data=pd.read_csv("Iris.csv")
data.head()

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [10]:
#Replacing categorical with numerical data 
data.loc[data["Species"]=="Iris-setosa","Species"]=0
data.loc[data["Species"]=="Iris-versicolor","Species"]=1
data.loc[data["Species"]=="Iris-virginica","Species"]=2

#Shuffling the data 
data=data.iloc[np.random.permutation(len(data))]
data.head()

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  Species
98    99            5.1           2.5            3.0           1.1        1
30    31            4.8           3.1            1.6           0.2        0
44    45            5.1           3.8            1.9           0.4        0
137  138            6.4           3.1            5.5           1.8        2
48    49            5.3           3.7            1.5           0.2        0

In [13]:

#Predictors and target 
X=data.iloc[:,1:5].values
y=data.iloc[:,5].values

#Normalization 
X_normalized=normalize(X,axis=0)
print("Examples of X_normalised\n",X_normalized[:3])

Examples of X_normalised
 [[ 0.07056264  0.06617903  0.05902813  0.06326647]
 [ 0.0664119   0.082062    0.03148167  0.01150299]
 [ 0.07056264  0.10059213  0.03738448  0.02300599]]


In [14]:
#Creating train and test data

total_length=len(data)
train_length=int(0.8*total_length)
test_length=int(0.2*total_length)

X_train=X_normalized[:train_length]
X_test=X_normalized[train_length:]
y_train=y[:train_length]
y_test=y[train_length:]


In [15]:
#Neural network module
from keras.models import Sequential 
from keras.layers import Dense,Activation,Dropout 
from keras.layers.normalization import BatchNormalization 
from keras.utils import np_utils
#Change the label to one hot vector
'''
[0]--->[1 0 0]
[1]--->[0 1 0]
[2]--->[0 0 1]
'''
y_train=np_utils.to_categorical(y_train,num_classes=3)
y_test=np_utils.to_categorical(y_test,num_classes=3)
print("Shape of y_train",y_train.shape)
print("Shape of y_test",y_test.shape)


Shape of y_train (120, 3)
Shape of y_test (30, 3)


In [17]:
#Building the neural network 
model=Sequential()
model.add(Dense(1000,input_dim=4,activation='relu'))
model.add(Dense(500,activation='relu'))
model.add(Dense(300,activation='relu'))
model.add(Dropout(0.2))
model.add(Dense(3,activation='softmax'))
model.compile(loss='categorical_crossentropy',optimizer='adam',metrics=['accuracy'])
model.summary()


_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_5 (Dense)              (None, 1000)              5000      
_________________________________________________________________
dense_6 (Dense)              (None, 500)               500500    
_________________________________________________________________
dense_7 (Dense)              (None, 300)               150300    
_________________________________________________________________
dropout_2 (Dropout)          (None, 300)               0         
_________________________________________________________________
dense_8 (Dense)              (None, 3)                 903       
Total params: 656,703
Trainable params: 656,703
Non-trainable params: 0
_________________________________________________________________


In [22]:
model.fit(X_train,y_train,validation_data=(X_test,y_test),batch_size=20,epochs=10,verbose=1)
prediction=model.predict(X_test)
length=len(prediction)
y_label=np.argmax(y_test,axis=1)
predict_label=np.argmax(prediction,axis=1)
accuracy=np.sum(y_label==predict_label)/length * 100 




Train on 120 samples, validate on 30 samples
Epoch 1/10
120/120 [==============================] - 0s 1ms/step - loss: 0.0492 - acc: 0.9750 - val_loss: 0.1218 - val_acc: 0.9667
Epoch 2/10
120/120 [==============================] - 0s 2ms/step - loss: 0.0413 - acc: 0.9833 - val_loss: 0.0942 - val_acc: 0.9667
Epoch 3/10
120/120 [==============================] - 0s 2ms/step - loss: 0.1123 - acc: 0.9667 - val_loss: 0.0637 - val_acc: 0.9333
Epoch 4/10
120/120 [==============================] - 0s 2ms/step - loss: 0.0648 - acc: 0.9667 - val_loss: 0.0645 - val_acc: 0.9667
Epoch 5/10
120/120 [==============================] - 0s 2ms/step - loss: 0.0511 - acc: 0.9750 - val_loss: 0.1121 - val_acc: 0.9667
Epoch 6/10
120/120 [==============================] - 0s 2ms/step - loss: 0.0409 - acc: 0.9833 - val_loss: 0.0761 - val_acc: 0.9667
Epoch 7/10
120/120 [==============================] - 0s 2ms/step - loss: 0.0477 - acc: 0.9750 - val_loss: 0.0896 - val_acc: 0.9667
Epoch 8/10
120/120 [===========

In [24]:
accuracy=np.sum(y_label==predict_label)/length * 100 
print("Accuracy of the dataset",accuracy )

Accuracy of the dataset 96.6666666667
